NAME: '_test3_peta'

DATASET:
  TYPE: 'pedes'
  NAME: 'NATIVE'
  TRAIN_SPLIT: 'trainval'
  VAL_SPLIT: 'test'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 256
  WIDTH: 128

RELOAD:
  TYPE: False
  PTH: "/content/upar_challenge/exp_result/PETA/swin_b_test3_peta/img_model/ckpt_max_multi_evavit_swinT_peta.pth"
  NAME: 'backbone'

BACKBONE:
  TYPE: 'swin_b' # swin_t/s/b

CLASSIFIER:
  NAME: 'linear'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'bceloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


#TRAIN:
#  CLIP_GRAD: True
#  MAX_EPOCH: 10
#  BATCH_SIZE: 32
#  OPTIMIZER:
#    TYPE: 'adam'
#    MOMENTUM: 0.9
#    WEIGHT_DECAY: 5e-4
#  LR_SCHEDULER:
#    TYPE: 'multistep'
#    LR_STEP: [10, 15]
#    LR_FT: 0.0001
#    LR_NEW: 0.0001
#  EMA:
#    ENABLE: False

TRAIN:
  CLIP_GRAD: True
  MAX_EPOCH: 3
  BATCH_SIZE: 16
  OPTIMIZER:
    TYPE: 'adam'
    WEIGHT_DECAY: 0.0005
  LR_SCHEDULER:
    TYPE: 'plateau'
    LR_FT: 0.000001
    LR_NEW: 0.000001
  EMA:
    ENABLE: False

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
